#MQ_PW
CAMERA_CFG_MQ=1129
CAMERA_CFG_RES_MQ=1130

IMAGE_HASH_REQ_MQ = 1131
IMAGE_HASH_RES_MQ=1132
#Message Type
TYPE_CAMERA_CFG=1
TYPE_CAMERA_CFG_RES=2

TYPE_IMAGE_HASH_REQ= 3
TYPE_IMAGE_HASH_RES=4
#----------------------------
#Header size
CAMERA_CONFIG_HEADER_SIZE = 6
CAMERA_CONFIG_RES_HEADER_SIZE = 1
IMAGE_HASH_REQ_BUFF_SIZE = 1
#----------------------------
#SIZE 
VGA = 0x01
HD = 0x02
CIF = 0x03
#----------------------------
#FORMAT
YUV420 = 0x21
#----------------------------
#IMAGE_HASH_REQUEST
IMAGE_HASH_REQ = 0x01
IMAGE_HASH_RES = 0x02
